name: Build and release to ghcr.io

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get short SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        run: |
          DOCKER_TAG="ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ steps.vars.outputs.sha_short }}"        
          docker buildx build \
            -t ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.sha_short }} \
            -t ghcr.io/${{ github.repository }}:latest
            .
